<?php

use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\smart_content\Segment;
use Drupal\smart_content\Entity\SegmentSetConfig;
/**
 * @file
 * Contains smart_content_paragraphs.install.
 */

/**
 * Implements hook_schema().
 */
function smart_content_paragraphs_schema() {
  $schema['smart_content_paragraphs_regions'] = [
    'description' => 'Region Details',
    'fields' => [
      'region' => [
        'type' => 'varchar',
        'length' => 60,
        'not null' => TRUE,
        'default' => '',
      ],
      'country' => [
        'type' => 'varchar',
        'length' => 60,
        'not null' => TRUE,
        'default' => '',
      ],
      'boundsNElat' => [
        'type' => 'varchar',
        'length' => 25,
        'not null' => TRUE,
        'default' => '',
      ],
      'boundsNElong' => [
        'type' => 'varchar',
        'length' => 25,
        'not null' => TRUE,
        'default' => '',
      ],
      'boundsSWlat' => [
        'type' => 'varchar',
        'length' => 25,
        'not null' => TRUE,
        'default' => '',
      ],
      'boundsSWlong' => [
        'type' => 'varchar',
        'length' => 25,
        'not null' => TRUE,
        'default' => '',
      ],
    ],
    'primary key' => [
      'region',
      'country',
    ],
  ];

  return $schema;
}

/**
 * Implements hook_uninstall().
 */
function smart_content_paragraphs_uninstall() {
  // Delete regions table if exist.
  \Drupal::database()->schema()
    ->dropTable('smart_content_paragraphs_regions');
}
/**
 * Implements hook_update_N().
 */
function smart_content_paragraphs_update_8001() {
  $entity_type = 'paragraph';
  $field_name = 'field_smart_content_conditions';

  $ids_old = \Drupal::entityQuery('smart_segment')->execute();
  foreach($ids_old as $id){
    $new = \Drupal::service('config.factory')->get("smart_content_segments.smart_segment.{$id}")->get('conditions');
    $uuid = \Drupal::service('uuid')->generate();
    \Drupal::service('config.factory')->rename("smart_content_segments.smart_segment.{$id}", "smart_content.smart_content.segment_set.{$id}");
    \Drupal::configFactory()->getEditable("smart_content.smart_content.segment_set.{$id}")
      ->set("settings.segments.{$uuid}.conditions", $new)
      ->set("settings.segments.{$uuid}.{$uuid}", $uuid)
      ->set("settings.segments.{$uuid}.weight", 0)
      ->set("settings.segments.{$uuid}.label", 1)
      ->set("settings.segments.{$uuid}.default", '')
      ->save();
    SegmentSetConfig::load($id)->save();
  }
  // Update field configuration.
  $config = \Drupal::configFactory()
    ->getEditable("field.storage.{$entity_type}.{$field_name}");
  $config->set('settings.target_type', 'smart_content_segment_set');
  $config->save(TRUE);

  // Update field storage configuration.
  FieldStorageConfig::loadByName($entity_type, $field_name)->save();

}

/**
 * Implements hook_uninstall().
 */
function smart_content_paragraphs_update_8002() {
  $extension_config = \Drupal::configFactory()->getEditable('core.extension');
  $module = $extension_config->get('module');
  if (isset($module['pce_geocloudflare'])) {
    unset($module['pce_geocloudflare']);
    $extension_config->set('module', $module);
    $extension_config->save();
  }
  \Drupal::keyValue('system.schema')->delete('pce_geocloudflare');

  $module_list = array(
    'pce_geolocation',
  );
  \Drupal::service('module_installer')->install($module_list);
}