<?php

/**
 * @file
 * Contains smart_content_paragraphs.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Http\Adapter\Guzzle6\Client;
use Geocoder\Provider\GoogleMaps\GoogleMaps;
use Geocoder\StatefulGeocoder;
use Geocoder\Query\GeocodeQuery;
use Drupal\Core\Database\Database;
use Drupal\smart_content\Segment;
use Drupal\smart_content\Entity\SegmentSetConfig;
use Drupal\smart_content\SegmentSetStorage\SegmentSetStorageManager;
/**
 * Implements hook_preprocess_node().
 */
function smart_content_paragraphs_preprocess_node(&$variables) {
  $variables['#attached']['library'][] = 'smart_content_paragraphs/personalization';
  $cloudflare_country_code = isset($_SERVER["HTTP_CF_IPCOUNTRY"]) ? $_SERVER["HTTP_CF_IPCOUNTRY"] : '';
  $variables['#attached']['drupalSettings']['smartContentParagraphs']['nid'][] = $variables['node']->id();
  $variables['#attached']['drupalSettings']['smartContentParagraphs']['cloudflareCountryCode'] = $cloudflare_country_code;
}

/**
 * Implements hook_preprocess_paragraph().
 */
function smart_content_paragraphs_preprocess_paragraph(&$variables) {
  $variables['attributes']['class'][] = 'paragraph--' . $variables['paragraph']->id();
}

/**
 * Altering the segment Add/Edit form's submit handler.
 */
function smart_content_paragraphs_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'smart_content_segment_set_add_form' || $form_id == 'smart_content_segment_set_edit_form') {
    $form['#attached']['library'][] = 'smart_content_paragraphs/personalization';
    $form['actions']['submit']['#submit'][] = 'smart_content_paragraphs_segment_form_save';
  }
}

/**
 * Custom submit handler for Segment Add/Edit form.
 */
function smart_content_paragraphs_segment_form_save($form, FormStateInterface $form_state) {
  $segment_set = $form_state->getStorage()['smart_content']['segment_set']->getSegments();
  $values = $form_state->getValues();
  foreach ($segment_set as $segment_id => $segment) {
    $conditions = $values['segment_set_settings']['segments'][$segment_id]['segment_settings']['condition_settings']['group']['plugin_form']['settings']['conditions'];
    foreach ($conditions as $condition_id => $condition) {
      if (strpos($condition_id, 'geobrowser:region') !== FALSE) {
        foreach ($condition as $condition_type) {         
          $region_name = $condition_type['value'];
          _store_region_details($region_name);
        }
      }
    }
  }
}

/**
 * Store the region details along with lat and long values.
 */
function _store_region_details($region_name) {
  $httpClient = new Client();
  $providers = \Drupal::entityTypeManager()->getStorage('geocoder_provider')->load('googlemaps');

  if (!empty($providers)) {
    $provider_config = $providers->get('configuration');
    $provider = new GoogleMaps($httpClient, NULL, $provider_config['apiKey']);
    $geocoder = new StatefulGeocoder($provider, 'en');

    $result = $geocoder->geocodeQuery(GeocodeQuery::create(str_replace(' ', '+', $region_name)));
    if ($result->count()) {
      $country = $result->first()->getCountry()->getName();
      if (!_region_exist($region_name, $country)) {
        $boundsNElat = $result->first()->getBounds()->getNorth();
        $boundsNElong = $result->first()->getBounds()->getEast();
        $boundsSWlat = $result->first()->getBounds()->getSouth();
        $boundsSWlong = $result->first()->getBounds()->getWest();

        $connection = Database::getConnection();
        $smart_content_paragraphs_regions = $connection->insert('smart_content_paragraphs_regions')->fields([
          'region' => $region_name,
          'country' => $country,
          'boundsNElat' => $boundsNElat,
          'boundsNElong' => $boundsNElong,
          'boundsSWlat' => $boundsSWlat,
          'boundsSWlong' => $boundsSWlong,
        ])->execute();
      }
    }
    return $smart_content_paragraphs_regions;
  }
  else {
    \Drupal::messenger()->addError(t("Please add the Googlemaps provider and configure Google API Key in <a href='@basepath/admin/config/system/geocoder/geocoder-provider' target='_blank'>Geocoder Provider</a> to save the region details", ['@basepath' => base_path()]), 'error', TRUE);
  }
}

/**
 * Function to check whether the Region and country names already exist or not.
 */
function _region_exist($region_name, $country) {
  $count = \Drupal::database()
  ->select('smart_content_paragraphs_regions')
  ->condition('region', $region_name)
  ->condition('country', $country)
  ->countQuery()
  ->execute()
  ->fetchField();

  return (bool) $count;
}

/**function smart_content_paragraphs_entity_access(\Drupal\Core\Entity\EntityInterface $entity, $operation, \Drupal\Core\Session\AccountInterface $account) {
  if ($operation = 'view') {
    return AccessResult::allowed();
  }
  return AccessResult::forbidden();
}**/
